site_name: possível app
site_url: https://example.com/

nav:
  - Home: 'pagina-inicial.md'
  - Atas: 'atas.md'
  - Planejamento do projeto: 'planejamento-projeto.md'
theme: readthedocs

extra_css:
  - 'css/custom.css'
